/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2021-03-26 22:40:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/PC/Desktop/N17DCCN160_TranMinhTuan/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp6/wtpwebapps/LapTopMinhTuan/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("jar:file:/C:/Users/PC/Desktop/N17DCCN160_TranMinhTuan/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp6/wtpwebapps/LapTopMinhTuan/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1390885082000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar", Long.valueOf(1519704125855L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1519704125836L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("<!-- Bootstrap style -->\r\n");
      out.write("<link id=\"callCss\" rel=\"stylesheet\"\r\n");
      out.write("\thref=\"themes/bootshop/bootstrap.min.css\" media=\"screen\" />\r\n");
      out.write("<link href=\"themes/css/base.css\" rel=\"stylesheet\" media=\"screen\" />\r\n");
      out.write("<!-- Bootstrap style responsive -->\r\n");
      out.write("<link href=\"themes/css/bootstrap-responsive.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"themes/css/font-awesome.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("<!-- Google-code-prettify -->\r\n");
      out.write("<link href=\"themes/js/google-code-prettify/prettify.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<!-- fav and touch icons -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"themes/images/ico/favicon.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\"\r\n");
      out.write("\thref=\"themes/images/ico/apple-touch-icon-144-precomposed.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\"\r\n");
      out.write("\thref=\"themes/images/ico/apple-touch-icon-114-precomposed.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\"\r\n");
      out.write("\thref=\"themes/images/ico/apple-touch-icon-72-precomposed.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\"\r\n");
      out.write("\thref=\"themes/images/ico/apple-touch-icon-57-precomposed.png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style type=\"text/css\" id=\"enject\">\r\n");
      out.write(".remove{\r\n");
      out.write("\tbackground-color: red;\r\n");
      out.write("}\r\n");
      out.write(".navbar-inner{\t\r\n");
      out.write("    background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#e0e6ea), color-stop(70%,#3086c1), to(#0d6098));\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("    width: 1170px;\r\n");
      out.write("  \tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-btn {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-icon {\r\n");
      out.write("    font-size: 1.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fa-cart-plus:before {\r\n");
      out.write("    content: \"\\f217\";\r\n");
      out.write("}\r\n");
      out.write(".nav-icon{\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("    right: 130px;\r\n");
      out.write("    top: 11px;\r\n");
      out.write("    font-size: 42px;\r\n");
      out.write("    color: #e80d0d;}\r\n");
      out.write(".cart-items {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 5px;\r\n");
      out.write("    right: 111px;\r\n");
      out.write("    background: #ffc800;\r\n");
      out.write("    padding: 0 5px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    width: 20px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("    width: 145px;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    background-color: #00aeef;\r\n");
      out.write("    padding: 0px 55px 0px 12px;\r\n");
      out.write("    line-height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title:before {\r\n");
      out.write("    border-color: transparent #ffffff transparent #b5595900;\r\n");
      out.write("    border-style: solid;\r\n");
      out.write("    border-width: 0px 30px 31px 0px;\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title1 {\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    border-bottom: 3px solid #00aeef;\r\n");
      out.write("    line-height: 33px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title1 span {\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    background-color: #00aeef;\r\n");
      out.write("    padding: 0 52px 0 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title1 span:before {\r\n");
      out.write("    border-color: transparent #ffffff transparent transparent;\r\n");
      out.write("    border-style: solid;\r\n");
      out.write("    border-width: 0 40px 33px 0;\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-right {\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-right:before{\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("    content: \" \";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-right:after{\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("    content: \" \";\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div id=\"footerSection\" style=\"height: 70px;>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\"\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"span3\" style=\"margin-left: 95px;\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"span3\" style=\"padding-top: 10px; margin-left: 200px;\">\r\n");
      out.write("\t\t\t\t<div class=\"pull-right\" style=\"font-size: 20px;\">\r\n");
      out.write("\t\t\t\t\t<b>Hotline hỗ trợ khách hàng</b>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<p class=\"pull-right\" style=\"margin-left: 34px;\">© LapTopminhtuan.com - 0121.332.1897 (từ\r\n");
      out.write("\t\t\t\t\t8h-21h, kể cả T7-CN)</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"socialMedia\" class=\"span3 pull-right\">\r\n");
      out.write("\t\t\t\t<h5>LIÊN HỆ VỚI CHÚNG TÔI</h5>\r\n");
      out.write("\t\t\t\t<a href=\"#\" target=\"blank\"><img width=\"60\" height=\"60\"\r\n");
      out.write("\t\t\t\t\tsrc=\"themes/images/facebook.png\" title=\"facebook\" alt=\"facebook\"></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" target=\"blank\"><img width=\"60\" height=\"60\"\r\n");
      out.write("\t\t\t\t\tsrc=\"themes/images/twitter.png\" title=\"twitter\" alt=\"twitter\"></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" target=\"blank\"><img width=\"60\" height=\"60\"\r\n");
      out.write("\t\t\t\t\tsrc=\"themes/images/youtube.png\" title=\"youtube\" alt=\"youtube\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Placed at the end of the document so the pages load faster ============================================= -->\r\n");
      out.write("<script src=\"themes/js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"themes/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"themes/js/google-code-prettify/prettify.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"themes/js/bootshop.js\"></script>\r\n");
      out.write("<script src=\"themes/js/jquery.lightbox-0.5.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"themes/js/jquery-1.7.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/user/footer.jsp(142,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.user.fullName != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<h5>TÀI KHOẢN</h5>\r\n");
          out.write("\t\t\t\t\t\t<a href=\"user/change-pass/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(".htm\">ĐỔI\r\n");
          out.write("\t\t\t\t\t\t\tMẬT KHẨU</a>\r\n");
          out.write("\t\t\t\t\t\t<a href=\"user/change-info/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(".htm\">CẬP\r\n");
          out.write("\t\t\t\t\t\t\tNHẬT THÔNG TIN</a>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    }
    return false;
  }
}
