/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2021-03-27 09:00:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/PC/Desktop/N17DCCN160_TranMinhTuan/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp6/wtpwebapps/LapTopMinhTuan/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1390885082000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar", Long.valueOf(1519704125855L));
    _jspx_dependants.put("jar:file:/C:/Users/PC/Desktop/N17DCCN160_TranMinhTuan/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp6/wtpwebapps/LapTopMinhTuan/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1390885082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmodelAttribute_005fmethod_005fid_005fenctype_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fpassword_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fcssClass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005ftype_005fpath_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmodelAttribute_005fmethod_005fid_005fenctype_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fpassword_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fcssClass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005ftype_005fpath_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmodelAttribute_005fmethod_005fid_005fenctype_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fpassword_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fcssClass.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005ftype_005fpath_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" />\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>LapTopMinhTuan</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t*[id$=errors]{\r\n");
      out.write("\t    margin-left: 10px;\r\n");
      out.write("\t\tcolor:red;\r\n");
      out.write("\t\tfont-style:italic;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div id=\"mainBody\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t<!--  -->\r\n");
      out.write("\t\t\t\t<div class=\"span9\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"user/home\">Trang chủ</a> <span class=\"divider\">/</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\">Đăng Ký</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<h3 class=\"title1\"> \r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\tĐăng ký tài khoản\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"well\">\r\n");
      out.write("\t\t\t\t\t\t");
      //  form:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmodelAttribute_005fmethod_005fid_005fenctype_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      try {
        _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_form_005fform_005f0.setParent(null);
        // /WEB-INF/views/user/register.jsp(39,6) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005fform_005f0.setAction("user/register");
        // /WEB-INF/views/user/register.jsp(39,6) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005fform_005f0.setMethod("post");
        // /WEB-INF/views/user/register.jsp(39,6) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005fform_005f0.setModelAttribute("register");
        // /WEB-INF/views/user/register.jsp(39,6) null
        _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "form-horizontal");
        // /WEB-INF/views/user/register.jsp(39,6) name = enctype type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005fform_005f0.setEnctype("multipart/form-data");
        // /WEB-INF/views/user/register.jsp(39,6) null
        _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "role", "form");
        // /WEB-INF/views/user/register.jsp(39,6) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005fform_005f0.setId("register");
        int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
          if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t<h4>Thông tin cá nhân</h4>\r\n");
              out.write("\t\t\t\t\t\t\t<h4 style=\"color: red;\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</h4>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">Họ và tên: <sup\r\n");
              out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red\">*</sup>\r\n");
              out.write("\t\t\t\t\t\t\t\t</label>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              if (_jspx_meth_form_005finput_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
                return;
              //  form:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              try {
                _jspx_th_form_005ferrors_005f0.setPageContext(_jspx_page_context);
                _jspx_th_form_005ferrors_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
                // /WEB-INF/views/user/register.jsp(51,60) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f0.setPath("fullName");
                int[] _jspx_push_body_count_form_005ferrors_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_form_005ferrors_005f0 = _jspx_th_form_005ferrors_005f0.doStartTag();
                  if (_jspx_th_form_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_form_005ferrors_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_form_005ferrors_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_form_005ferrors_005f0.doFinally();
                }
              } finally {
                _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_form_005ferrors_005f0);
              }
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">Tên đăng nhập: <sup\r\n");
              out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red\">*</sup></label>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              if (_jspx_meth_form_005finput_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
                return;
              //  form:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f1 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              try {
                _jspx_th_form_005ferrors_005f1.setPageContext(_jspx_page_context);
                _jspx_th_form_005ferrors_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
                // /WEB-INF/views/user/register.jsp(59,36) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f1.setPath("id");
                int[] _jspx_push_body_count_form_005ferrors_005f1 = new int[] { 0 };
                try {
                  int _jspx_eval_form_005ferrors_005f1 = _jspx_th_form_005ferrors_005f1.doStartTag();
                  if (_jspx_th_form_005ferrors_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_form_005ferrors_005f1[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_form_005ferrors_005f1.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_form_005ferrors_005f1.doFinally();
                }
              } finally {
                _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_form_005ferrors_005f1);
              }
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">Mật khẩu: <sup\r\n");
              out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red\">*</sup></label>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              if (_jspx_meth_form_005fpassword_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
                return;
              //  form:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f2 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              try {
                _jspx_th_form_005ferrors_005f2.setPageContext(_jspx_page_context);
                _jspx_th_form_005ferrors_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
                // /WEB-INF/views/user/register.jsp(67,59) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f2.setPath("password");
                int[] _jspx_push_body_count_form_005ferrors_005f2 = new int[] { 0 };
                try {
                  int _jspx_eval_form_005ferrors_005f2 = _jspx_th_form_005ferrors_005f2.doStartTag();
                  if (_jspx_th_form_005ferrors_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_form_005ferrors_005f2[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_form_005ferrors_005f2.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_form_005ferrors_005f2.doFinally();
                }
              } finally {
                _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_form_005ferrors_005f2);
              }
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">Địa chỉ Email: <sup\r\n");
              out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red\">*</sup></label>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              if (_jspx_meth_form_005finput_005f2(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
                return;
              //  form:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f3 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              try {
                _jspx_th_form_005ferrors_005f3.setPageContext(_jspx_page_context);
                _jspx_th_form_005ferrors_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
                // /WEB-INF/views/user/register.jsp(75,36) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f3.setPath("email");
                int[] _jspx_push_body_count_form_005ferrors_005f3 = new int[] { 0 };
                try {
                  int _jspx_eval_form_005ferrors_005f3 = _jspx_th_form_005ferrors_005f3.doStartTag();
                  if (_jspx_th_form_005ferrors_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_form_005ferrors_005f3[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_form_005ferrors_005f3.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_form_005ferrors_005f3.doFinally();
                }
              } finally {
                _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_form_005ferrors_005f3);
              }
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">Ngày sinh: <sup\r\n");
              out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red\">*</sup>\r\n");
              out.write("\t\t\t\t\t\t\t\t</label>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              if (_jspx_meth_form_005finput_005f3(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
                return;
              //  form:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f4 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              try {
                _jspx_th_form_005ferrors_005f4.setPageContext(_jspx_page_context);
                _jspx_th_form_005ferrors_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
                // /WEB-INF/views/user/register.jsp(84,61) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f4.setPath("birthday");
                int[] _jspx_push_body_count_form_005ferrors_005f4 = new int[] { 0 };
                try {
                  int _jspx_eval_form_005ferrors_005f4 = _jspx_th_form_005ferrors_005f4.doStartTag();
                  if (_jspx_th_form_005ferrors_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_form_005ferrors_005f4[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_form_005ferrors_005f4.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_form_005ferrors_005f4.doFinally();
                }
              } finally {
                _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_form_005ferrors_005f4);
              }
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">Số điện thoại: <sup\r\n");
              out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red\">*</sup>\r\n");
              out.write("\t\t\t\t\t\t\t\t</label>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              if (_jspx_meth_form_005finput_005f4(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
                return;
              //  form:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f5 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              try {
                _jspx_th_form_005ferrors_005f5.setPageContext(_jspx_page_context);
                _jspx_th_form_005ferrors_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
                // /WEB-INF/views/user/register.jsp(93,63) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f5.setPath("numberPhone");
                int[] _jspx_push_body_count_form_005ferrors_005f5 = new int[] { 0 };
                try {
                  int _jspx_eval_form_005ferrors_005f5 = _jspx_th_form_005ferrors_005f5.doStartTag();
                  if (_jspx_th_form_005ferrors_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_form_005ferrors_005f5[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_form_005ferrors_005f5.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_form_005ferrors_005f5.doFinally();
                }
              } finally {
                _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_form_005ferrors_005f5);
              }
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">Giới tính: <sup\r\n");
              out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red\">*</sup></label>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              if (_jspx_meth_form_005fselect_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              //  form:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f6 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              try {
                _jspx_th_form_005ferrors_005f6.setPageContext(_jspx_page_context);
                _jspx_th_form_005ferrors_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
                // /WEB-INF/views/user/register.jsp(106,9) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f6.setPath("gender");
                int[] _jspx_push_body_count_form_005ferrors_005f6 = new int[] { 0 };
                try {
                  int _jspx_eval_form_005ferrors_005f6 = _jspx_th_form_005ferrors_005f6.doStartTag();
                  if (_jspx_th_form_005ferrors_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_form_005ferrors_005f6[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_form_005ferrors_005f6.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_form_005ferrors_005f6.doFinally();
                }
              } finally {
                _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_form_005ferrors_005f6);
              }
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">Địa chỉ: <sup\r\n");
              out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red\">*</sup></label>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              if (_jspx_meth_form_005fselect_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              //  form:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f7 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              try {
                _jspx_th_form_005ferrors_005f7.setPageContext(_jspx_page_context);
                _jspx_th_form_005ferrors_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
                // /WEB-INF/views/user/register.jsp(182,9) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f7.setPath("address");
                int[] _jspx_push_body_count_form_005ferrors_005f7 = new int[] { 0 };
                try {
                  int _jspx_eval_form_005ferrors_005f7 = _jspx_th_form_005ferrors_005f7.doStartTag();
                  if (_jspx_th_form_005ferrors_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_form_005ferrors_005f7[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_form_005ferrors_005f7.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_form_005ferrors_005f7.doFinally();
                }
              } finally {
                _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_form_005ferrors_005f7);
              }
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">Hình ảnh: <sup\r\n");
              out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red\">*</sup></label>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<input id=\"photo\" name=\"file_image\" type=\"file\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" />");
              //  form:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f8 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              try {
                _jspx_th_form_005ferrors_005f8.setPageContext(_jspx_page_context);
                _jspx_th_form_005ferrors_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
                // /WEB-INF/views/user/register.jsp(191,33) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f8.setPath("photo");
                int[] _jspx_push_body_count_form_005ferrors_005f8 = new int[] { 0 };
                try {
                  int _jspx_eval_form_005ferrors_005f8 = _jspx_th_form_005ferrors_005f8.doStartTag();
                  if (_jspx_th_form_005ferrors_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_form_005ferrors_005f8[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_form_005ferrors_005f8.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_form_005ferrors_005f8.doFinally();
                }
              } finally {
                _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_form_005ferrors_005f8);
              }
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t");
              if (_jspx_meth_form_005finput_005f5(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<input class=\"btn btn-large btn-success\" type=\"submit\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Đăng Ký\">\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t");
              int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_form_005fform_005f0.doFinally();
        }
      } finally {
        _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmodelAttribute_005fmethod_005fid_005fenctype_005fclass_005faction.reuse(_jspx_th_form_005fform_005f0);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--  -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"assets/jquery-ui/jquery-ui.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"assets/jquery-ui/jquery-ui.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\".birthday\").datepicker({\r\n");
      out.write("\t\t\tdateFormat : 'dd/mm/yy'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"input#birthday\").datepicker({\r\n");
      out.write("\t\t\tdateFormat : 'dd/mm/yy'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_form_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/user/register.jsp(50,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f0.setPath("fullName");
      // /WEB-INF/views/user/register.jsp(50,9) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f0.setId("fullName");
      // /WEB-INF/views/user/register.jsp(50,9) null
      _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "placeholder", "Full Name");
      // /WEB-INF/views/user/register.jsp(50,9) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f0.setCssClass("form-control");
      int[] _jspx_push_body_count_form_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f0 = _jspx_th_form_005finput_005f0.doStartTag();
        if (_jspx_th_form_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.reuse(_jspx_th_form_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_form_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/user/register.jsp(58,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f1.setPath("id");
      // /WEB-INF/views/user/register.jsp(58,9) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f1.setId("id");
      // /WEB-INF/views/user/register.jsp(58,9) null
      _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "placeholder", "Username");
      // /WEB-INF/views/user/register.jsp(58,9) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f1.setCssClass("form-control");
      int[] _jspx_push_body_count_form_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f1 = _jspx_th_form_005finput_005f1.doStartTag();
        if (_jspx_th_form_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.reuse(_jspx_th_form_005finput_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fpassword_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:password
    org.springframework.web.servlet.tags.form.PasswordInputTag _jspx_th_form_005fpassword_005f0 = (org.springframework.web.servlet.tags.form.PasswordInputTag) _005fjspx_005ftagPool_005fform_005fpassword_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.PasswordInputTag.class);
    try {
      _jspx_th_form_005fpassword_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fpassword_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/user/register.jsp(66,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fpassword_005f0.setPath("password");
      // /WEB-INF/views/user/register.jsp(66,9) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fpassword_005f0.setId("password");
      // /WEB-INF/views/user/register.jsp(66,9) null
      _jspx_th_form_005fpassword_005f0.setDynamicAttribute(null, "placeholder", "Password");
      // /WEB-INF/views/user/register.jsp(66,9) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fpassword_005f0.setCssClass("form-control");
      int[] _jspx_push_body_count_form_005fpassword_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fpassword_005f0 = _jspx_th_form_005fpassword_005f0.doStartTag();
        if (_jspx_th_form_005fpassword_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fpassword_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fpassword_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fpassword_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fform_005fpassword_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.reuse(_jspx_th_form_005fpassword_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_form_005finput_005f2.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/user/register.jsp(74,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f2.setPath("email");
      // /WEB-INF/views/user/register.jsp(74,9) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f2.setId("email");
      // /WEB-INF/views/user/register.jsp(74,9) null
      _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "placeholder", "Email Address");
      // /WEB-INF/views/user/register.jsp(74,9) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f2.setCssClass("form-control");
      int[] _jspx_push_body_count_form_005finput_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f2 = _jspx_th_form_005finput_005f2.doStartTag();
        if (_jspx_th_form_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f2.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.reuse(_jspx_th_form_005finput_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_form_005finput_005f3.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/user/register.jsp(83,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f3.setPath("birthday");
      // /WEB-INF/views/user/register.jsp(83,9) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f3.setId("birthday");
      // /WEB-INF/views/user/register.jsp(83,9) null
      _jspx_th_form_005finput_005f3.setDynamicAttribute(null, "placeholder", "dd/mm/yyyy");
      // /WEB-INF/views/user/register.jsp(83,9) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f3.setCssClass("form-control");
      int[] _jspx_push_body_count_form_005finput_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f3 = _jspx_th_form_005finput_005f3.doStartTag();
        if (_jspx_th_form_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f3.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.reuse(_jspx_th_form_005finput_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f4 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_form_005finput_005f4.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/user/register.jsp(92,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f4.setPath("numberPhone");
      // /WEB-INF/views/user/register.jsp(92,9) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f4.setId("numberPhone");
      // /WEB-INF/views/user/register.jsp(92,9) null
      _jspx_th_form_005finput_005f4.setDynamicAttribute(null, "placeholder", "Number Phone");
      // /WEB-INF/views/user/register.jsp(92,9) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f4.setCssClass("form-control");
      int[] _jspx_push_body_count_form_005finput_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f4 = _jspx_th_form_005finput_005f4.doStartTag();
        if (_jspx_th_form_005finput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f4.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fcssClass_005fnobody.reuse(_jspx_th_form_005finput_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fselect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:select
    org.springframework.web.servlet.tags.form.SelectTag _jspx_th_form_005fselect_005f0 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fcssClass.get(org.springframework.web.servlet.tags.form.SelectTag.class);
    try {
      _jspx_th_form_005fselect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/user/register.jsp(101,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fselect_005f0.setPath("gender");
      // /WEB-INF/views/user/register.jsp(101,9) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fselect_005f0.setCssClass("form-control");
      int[] _jspx_push_body_count_form_005fselect_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fselect_005f0 = _jspx_th_form_005fselect_005f0.doStartTag();
        if (_jspx_eval_form_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0\">-- Chọn --</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">Nam</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">Nữ</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_form_005fselect_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fselect_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fselect_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fselect_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fcssClass.reuse(_jspx_th_form_005fselect_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fselect_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:select
    org.springframework.web.servlet.tags.form.SelectTag _jspx_th_form_005fselect_005f1 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fcssClass.get(org.springframework.web.servlet.tags.form.SelectTag.class);
    try {
      _jspx_th_form_005fselect_005f1.setPageContext(_jspx_page_context);
      _jspx_th_form_005fselect_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/user/register.jsp(115,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fselect_005f1.setPath("address");
      // /WEB-INF/views/user/register.jsp(115,9) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fselect_005f1.setCssClass("form-control");
      int[] _jspx_push_body_count_form_005fselect_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fselect_005f1 = _jspx_th_form_005fselect_005f1.doStartTag();
        if (_jspx_eval_form_005fselect_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">-- Chọn --</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"TP Can Tho\">TP. Cần Thơ</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"TP Da Nang\">TP. Đà Nẵng</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"TP Hai Phong\">TP. Hải Phòng</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"TP Ha Noi\">TP. Hà Nội</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"TP Ho Chi Minh\">TP. HCM</option>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"An Giang\">An Giang</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Ba Ria - Vung Tau\">Bà Rịa - Vũng Tàu</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Bac Giang\">Bắc Giang</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Ban Kan\">Bắc Kạn</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Bac Lieu\">Bạc Liêu</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Bac Ninh\">Bắc Ninh</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Ben Tre\">Bến Tre</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Binh Dinh\">Bình Định</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Binh Duong\">Bình Dương</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Binh Phuoc\">Bình Phước</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Binh Thuan\">Bình Thuận</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Ca Mau\">Cà Mau</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Cao Bang\">Cao Bằng</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Dak Lak\">Đắk Lắk</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Dak Nong\">Đắk Nông</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Dien Bien\">Điện Biên</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Dong Nai\">Đồng Nai</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Dong Thap\">Đồng Tháp</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Gia Lai\">Gia Lai</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Ha Giang\">Hà Giang</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Ha Nam\">Hà Nam</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Ha Tinh\">Hà Tĩnh</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Hai Duong\">Hải Dương</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Hau Giang\">Hậu Giang</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Hoa Binh\">Hòa Bình</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Hung Yen\">Hưng Yên</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Khanh Hoa\">Khánh Hòa</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Kien Giang\">Kiên Giang</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Kon Tum\">Kon Tum</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Lai Chau\">Lai Châu</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Lam Dong\">Lâm Đồng</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Lang Son\">Lạng Sơn</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Lao Cai\">Lào Cai</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Long An\">Long An</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Nam Dinh\">Nam Định</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Nghe An\">Nghệ An</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Ninh Binh\">Ninh Bình</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Ninh Thuan\">Ninh Thuận</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Phu Tho\">Phú Thọ</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Quang Binh\">Quảng Bình</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Quang Nam\">Quảng Nam</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Quang Ngai\">Quảng Ngãi</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Quang Ninh\">Quảng Ninh</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Quang Tri\">Quảng Trị</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Soc Trang\">Sóc Trăng</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Son La\">Sơn La</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Tay Ninh\">Tây Ninh</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Thai Binh\">Thái Bình</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Thai Nguyen\">Thái Nguyên</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Thanh Hoa\">Thanh Hóa</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Thua Thien Hue\">Thừa Thiên Huế</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Tien Giang\">Tiền Giang</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Tra Vinh\">Trà Vinh</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Tuyen Quang\">Tuyên Quang</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Vinh Long\">Vĩnh Long</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Vinh Phuc\">Vĩnh Phúc</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Yen Bai\">Yên Bái</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Phu Yen\">Phú Yên</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_form_005fselect_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fselect_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fselect_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fselect_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fselect_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fcssClass.reuse(_jspx_th_form_005fselect_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f5 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005ftype_005fpath_005fname_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    try {
      _jspx_th_form_005finput_005f5.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/user/register.jsp(195,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f5.setPath("activated");
      // /WEB-INF/views/user/register.jsp(195,7) null
      _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "type", "hidden");
      // /WEB-INF/views/user/register.jsp(195,7) null
      _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "name", "activated");
      // /WEB-INF/views/user/register.jsp(195,7) null
      _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "value", "false");
      int[] _jspx_push_body_count_form_005finput_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f5 = _jspx_th_form_005finput_005f5.doStartTag();
        if (_jspx_th_form_005finput_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f5.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005ftype_005fpath_005fname_005fnobody.reuse(_jspx_th_form_005finput_005f5);
    }
    return false;
  }
}
